//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.CourseComments = new HashSet<CourseComments>();
        }
    
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public int CategoryID { get; set; }
        public string Description { get; set; }
        public short Hours { get; set; }
        public Nullable<int> SessionID { get; set; }
    
        public virtual CourseCategory CourseCategory { get; set; }
        public virtual CourseSession CourseSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseComments> CourseComments { get; set; }
    }
}
