//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseComments
    {
        public int CommentID { get; set; }
        public int CourseID { get; set; }
        public int UserID { get; set; }
        public byte Score { get; set; }
        public string Text { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
